import {OrderedMap} from 'immutable';

export const CATEGORY_BRAND_ACTIONS = {
  FETCH_BRANDS_BY_CATEGORY: 'FETCH_BRANDS_BY_CATEGORY',
  FETCHED_BRANDS_BY_CATEGORY: 'FETCHED_BRANDS_BY_CATEGORY',
  FAILED_FETCH_BRANDS_BY_CATEGORY: 'FAILED_FETCH_BRANDS_BY_CATEGORY',
  FETCH_BRANDS: 'FETCH_BRANDS',
  FETCHED_BRANDS: 'FETCHED_BRANDS',
  FAILED_FETCH_BRANDS: 'FAILED_FETCH_BRANDS',
  FETCH_BRANDS_ALPHABETS: 'FETCH_BRANDS_ALPHABETS',
  FETCHED_BRANDS_ALPHABETS: 'FETCHED_BRANDS_ALPHABETS',
  FAILED_FETCH_BRANDS_ALPHABETS: 'FAILED_FETCH_BRANDS_ALPHABETS',
};

export const CATEGORIES = new OrderedMap({
  122000000: {
    categoryId: '122000000',
    category: 'Safety',
  },
  260000000: {
    categoryId: '260000000',
    category: 'Electricals',
  },
});

export const ALPHABETS = [65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76];
