export const NOTIFICATIONS_ACTIONS = {
  FETCH_NOTIFICATIONS: 'FETCH_NOTIFICATIONS',
  FETCHED_NOTIFICATIONS: 'FETCHED_NOTIFICATIONS',
  FAILED_FETCH_NOTIFICATIONS: 'FAILED_FETCH_NOTIFICATIONS',
  MARK_READ: 'MARK_READ',
  MARK_BULK_READ: 'MARK_BULK_READ',
  DELETE_NOTIFICATION: 'DELETE_NOTIFICATION',
  DELETE_BULK: 'DELETE_BULK'
};
