export const ORDERS_ACTIONS = {
  FETCH_ORDERS: 'FETCH_ORDERS',
  FETCHED_ORDERS: 'FETCHED_ORDERS',
  FAILED_FETCH_ORDERS: 'FAILED_FETCH_ORDERS',

  FETCH_TAB_COUNT: 'FETCH_TAB_COUNT',
  FETCHED_TAB_COUNT: 'FETCHED_TAB_COUNT',
  FAILED_FETCH_TAB_COUNT: 'FAILED_FETCH_TAB_COUNT',
};
