export const PROFILE_ACTIONS = {
  FETCH_PROFILE: 'FETCH_PROFILE',
  FETCHED_PROFILE: 'FETCHED_PROFILE',
  FAILED_FETCH_PROFILE: 'FAILED_FETCH_PROFILE',

  FETCH_BUSINESS_DETAILS: 'FETCH_BUSINESS_DETAILS',
  FETCHED_BUSINESS_DETAILS: 'FETCHED_BUSINESS_DETAILS',
  FAILED_FETCH_BUSINESS_DETAILS: 'FAILED_FETCH_BUSINESS_DETAILS',

  FETCH_UPDATE_BUSINESS_DETAILS: 'FETCH_UPDATE_BUSINESS_DETAILS',
  FETCHED_UPDATE_BUSINESS_DETAILS: 'FETCHED_UPDATE_BUSINESS_DETAILS',
  FAILED_FETCH_UPDATE_BUSINESS_DETAILS: 'FAILED_FETCH_UPDATE_BUSINESS_DETAILS',
};
